### ISSUE TITLE
Restlichen Modelle trainieren

### ISSUE THREAD

**Issue by gabrieltorresgamez** [AdversarialAttacks/main#4]

**Comment by 7ben18** [comment]
- 2 Datensätze
- 6 Familienmodelle 
- 2 bis 3 Modelle pro Familienmodelle
- 3 Hyperparameter  (Nur Learningrate, Regularisierungsparameter L2 und Dropout nicht berücksichtigt, 

Ergibt: 2 * 6 * 2 oder 3 * 3 = 72 oder 108 Runs

Schätzung pro Run: 20 Minuten auf Lambda Cloud auf A10. 

Erigbt: bei 72 Runs 24h! => Pro Familienmodell 4h Laufzeit!
