### ISSUE TITLE
Explorative Datenanalyse Part 1

### ISSUE THREAD

**Issue by gabrieltorresgamez** [AdversarialAttacks/main#5]

**Comment by 7ben18** [comment]
Unter src/utils/eda.py 
Class *ExplorativeDataAnalysis* geschrieben für die Qualitative Analyse (Plots ohne und mit Pertubation) geschrieben. (Random Pertubation, bis wir die richtige Pertubation haben) + Histogramm des Bildes

Class *AnalysePertubation* in Entwurfsphase
Idee: Analysieren der Pertubationen untereinander und einzeln
